# Generated by Django 5.2.3 on 2025-07-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_question_answer_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answers',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='answers',
            unique_together={('question', 'text')},
        ),
    ]
